### ISSUE TITLE
お問合せフォーム

### ISSUE THREAD

**Issue by w-shaulabg** [w-shaulabg/applications#2]
## テスト観点と期待値と結果
| テスト観点 | 期待値 | 
| --- | --- | 
| index.phpファイルが実行された時 | お問い合わせフォームが表示されること。タイトルフォーム、Emailフォーム、お問い合わせ内容フォーム、送信ボタンがお問い合わせフォーム内にはあること。 | 
| お問い合わせフォームの送信ボタンがクリックされた時 | complete.phpにページ遷移すること。 | 
| お問い合わせフォームの送信ボタンがクリックされた時 | complete.phpにpost送信でタイトルフォーム、Emailフォーム、お問い合わせ内容フォームに入力されたデータが送信されること。 | 
|お問合せフォームの送信ボタンがクリックされた時|DBにタイトル及びEメールアドレス並びにお問い合わせ内容を保存すること。|
|お問合せフォームの記載内容の全て、もしくはいずれかに記載漏れがあった場合に送信ボタンがクリックされた時|エラーメッセージを表示すること。|
| 送信完了画面の送信画面へのボタンがクリックされた時 | index.phpのページに遷移すること。|
| 送信完了画面の送信履歴へのボタンがクリックされた時 | historiy.phpのページに遷移すること。|
|お問合せフォームの入力データが全て存在する場合に、送信ボタンがクリックされた時| 「送信完了！！」の表示と「送信画面へ(index.phpへ繋がるリンク)」と「送信履歴へ(history.phpに繋がるリンク)」を表示する。|
|history.phpが実行され、contactsテーブルにデータが存在する時| タイトルとお問合せ内容の履歴を表示する。|
|history.phpが実行され、contactsテーブルにデータが存在しない時| 送信履歴はありません。と表示する。|
|history.phpで「戻る」ボタンを押下した時|index.phpのページに遷移すること。|

## チェック項目
- [ ] PR(プルリク)にReviewersを設定しましたか?
- [ ] PRにAssigneesを設定しましたか?
- [ ] PRにProjectsを設定しましたか?
- [ ] PRに[テスト観点と期待値と結果]を抜け漏れなく書いたか確認しましたか?(抜け漏れなく書けたという証明はできますか?)
- [ ] PRに実際のブラウザ画面の画像や動画を載せましたか?(見た目を実装時た場合は画像、処理の実装をした場合は、動画を載せましょう!)

**Comment by gotokouichi** [comment]
こちらも確認させていただきました！😊

２点ほど修正いただきたい点があります！✏️
============
１.テスト観点のキャプチャを共有いただいているかと思うのですが、キャプチャを貼り付けていただいた箇所に**直接マークダウンで記載いただくよう**お願いいたします！😊

お問合せフォームの使用のページにマークダウンの記法のテンプレートがあるので、こちらを参考にしていただければと思います！✨
https://round-petunia-b6f.notion.site/afd7bcb5dd614b94b61bc7f0c21d0966
----------------

2.送信完了ページ、送信履歴ページの機能に関するテスト観点についても追記していただくようお願いいたします！😁

============
